### ISSUE TITLE
[BUG]敌方先制反潜伤害没计算

### ISSUE THREAD

**Issue by slime7** [Yoctillion/BattleInfoPlugin#2]
地方先制反潜战斗数据
[ec_battle.zip](https://github.com/Yoctillion/BattleInfoPlugin/files/772821/ec_battle.zip)

**Comment by Yoctillion** [comment]
更新了 [敌先制对潜](https://github.com/Yoctillion/BattleInfoPlugin/commit/668118cc23d1d0cc7e121da13e18cf72c61019bc) 可以试一下
