### ISSUE TITLE
Change in API

### ISSUE THREAD

**Issue by SquidFish** [Yoctillion/BattleInfoPlugin#3]
Hi,

There is a change in API for the newest update of Kancolle.  The plugin is not working as it should now. Hope you can check it out.

![enemy](https://user-images.githubusercontent.com/32428830/32984000-d5342146-ccd8-11e7-91d1-0872ca64fdfa.PNG)

This is the only data showed on the plugin after a battle.

**Comment by Madmanmayson** [comment]
idk if Yoctillion is still working on this or not but I'm working on exploring the changes in the API and will try to make a PR to here (I'll have to probably make a new fork since mine already has other changes to it) but hopefully I'll have it working by the end of the day.

**Comment by Madmanmayson** [comment]
So far I've gotten it working for 6 and 7 ship fleets (I'm only on E2 right now so I don't have any combined fleet data to work with and experiment with ship indexes yet) and made an update release for my own KCV though I can't and won't guarantee it will work with any other versions. After getting combined fleets working I'll work on a generalized one and make a PR for here
